### ISSUE TITLE
CSDN 竟然有人用博主代码 收费才能观看

### ISSUE THREAD

**Issue by leipeng101** [huanghyw/jd_seckill#75]
https://blog.csdn.net/weixin_35770067/article/details/111639974

不知道是不是博主本人。

**Comment by huanghyw** [comment]
不是本人

**Comment by 32begin** [comment]
我换了账号，取出来的eid, fp参数，发现和之前的账号是一模一样的，这个有问题吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huanghyw/jd_seckill"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月25日(星期五) 下午2:12
收件人:&nbsp;"huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [huanghyw/jd_seckill] CSDN 竟然有人用博主代码 收费才能观看 (#75)





 
不是本人

**Comment by huanghyw** [comment]
已举报。
此举强制收费行为严重违反GPL3.0协议，并且特别申明中也说了不允许转载。

**Comment by leipeng101** [comment]
在哪里举报？我也去

**Comment by huanghyw** [comment]
> 我换了账号，取出来的eid, fp参数，发现和之前的账号是一模一样的，这个有问题吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "huanghyw/jd_seckill" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月25日(星期五) 下午2:12 收件人:&nbsp;"huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [huanghyw/jd_seckill] CSDN 竟然有人用博主代码 收费才能观看 (#75) 不是本人 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

和主题无关的问题下次最好单独提交Issues。

通过我的观察和其他使用者反馈，eid是可能会变得，但是同浏览器fp不变，fp可能是通过硬件算法得出的用户唯一标识。
所以你这个是正常的，不放心可以一段时间更新一次eid。

**Comment by huanghyw** [comment]
> 在哪里举报？我也去

文章下面就有举报按钮

**Comment by huanghyw** [comment]
> > 在哪里举报？我也去
> 
> 文章下面就有举报按钮

![image](https://user-images.githubusercontent.com/7189743/103122721-6ce9f500-46bc-11eb-8a96-941a5eb9c297.png)

**Comment by 32begin** [comment]
不同的账号eid相同，不是很容易被识别出是同一个人了吗？如何才能更新成不同的eid呢？我昨天和今天登录了两个账号，取出来的eid和fp是完全一样的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huanghyw/jd_seckill"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月25日(星期五) 下午2:20
收件人:&nbsp;"huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;;
抄送:&nbsp;"阿杜"<523745837@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [huanghyw/jd_seckill] CSDN 竟然有人用博主代码 收费才能观看 (#75)





  
我换了账号，取出来的eid, fp参数，发现和之前的账号是一模一样的，这个有问题吗？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "huanghyw/jd_seckill" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月25日(星期五) 下午2:12 收件人:&nbsp;"huanghyw/jd_seckill"<jd_seckill@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [huanghyw/jd_seckill] CSDN 竟然有人用博主代码 收费才能观看 (#75) 不是本人 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
和主题无关的问题下次最好单独提交Issues。
 
通过我的观察和其他使用者反馈，eid是可能会变得，但是同浏览器fp不变，fp可能是通过硬件算法得出的用户唯一标识。
 所以你这个是正常的，不放心可以一段时间更新一次eid。

**Comment by huanghyw** [comment]
用虚拟机可以解决这个问题

**Comment by huanghyw** [comment]
联系CSDN文章已下架了，多谢楼主举报 :)

**Comment by Wwzb** [comment]
> > 我换了账号，取出来的eid, fp参数，发现和之前的账号是一模一样的，这个有问题吗？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "huanghyw/jd_seckill" <[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年12月25日(星期五) 下午2:12 收件人: "huanghyw/jd_seckill"<[jd_seckill@noreply.github.com](mailto:jd_seckill@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: Re: [huanghyw/jd_seckill] CSDN 竟然有人用博主代码 收费才能观看 (#75) 不是本人 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 和主题无关的问题下次最好单独提交Issues。
> 
> 通过我的观察和其他使用者反馈，eid是可能会变得，但是同浏览器fp不变，fp可能是通过硬件算法得出的用户唯一标识。
> 所以你这个是正常的，不放心可以一段时间更新一次eid。

同浏览器是eid不会变，fp是不定期会变的，甚至改个浏览器的分辨率（如打开F12的终端模式）fp都会发生改变

**Comment by XiaoHb233** [comment]
> 联系CSDN文章已下架了，多谢楼主举报 :)
https://blog.csdn.net/weixin_35770067/article/details/111722109?ops_request_misc=%25257B%252522request%25255Fid%252522%25253A%252522160906051216780273352096%252522%25252C%252522scm%252522%25253A%25252220140713.130102334.pc%25255Fblog.%252522%25257D&request_id=160906051216780273352096&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~blog~first_rank_v2~rank_v29-1-111722109.pc_v2_rank_blog_default&utm_term=%E6%8A%A2%E8%B4%AD
楼主，这个是不是你的，我看文案和你差不多，也是收费的
